name = "english-writing-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "english-writing-db"
database_id = "a31d48b9-a17a-45a8-9c09-55bcd0512637"

[vars]
