name = "roysoft-review-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "roysoft-review-db"
database_id = "a6b76a19-fb14-4070-ad17-5728dbfaca27"

[vars]
